<img src="https://raw.githubusercontent.com/dvgodoy/PyTorch101_ODSC_Europe2020/master/images/linear_dogs.jpg" height="300"> 


# Андан на экономе

## Семинар 2: numpy

In [1]:
import numpy as np

## Зачем нужен этот пакет? 

`numpy` — библиотека, позволяющая удобно работать с многомерными массивами и матрицами, содержащая математические функции. Кроме того, `numpy` позволяет векторизовать многие вычисления и пригождается в анализе данных.

In [2]:
x = [1, 2, 3]
y = [4, 5, 6]

print(x + y) # списки объединились вмесссте
print(3 * x) # список продублировался трижды 
type(x)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


list

In [3]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y) # в случае numpy поэлементное сложение
print(3 * x) # каждый элемент умножился на число
type(x)

[5 7 9]
[3 6 9]


numpy.ndarray

Работает более быстро.

In [4]:
x = np.arange(10**7)
x[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
y = list(x)
y[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
%%timeit 
sum(y)

175 ms ± 8.52 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
%%timeit 
np.sum(x)

1.38 ms ± 4.16 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


NumPy работает быстро по нескольким причинам:
* Массивы хранятся в непрерывном участке памяти, а все элементы имеют один и тот же тип
* Для вычислений по возможности используются библиотеки линейной алгебры вроде BLAS

# 1. Вектора и матрицы

Посмотрим на основы работы с матрицами и векторами подробнее!

## 1.1 Вектора

Векторно работает не только сложение, но и все другие операции. 

In [8]:
x = np.array([1, -10, 3, 0, 1, 75, 3])
x[3:6]

array([ 0,  1, 75])

In [9]:
x[x > 0]

array([ 1,  3,  1, 75,  3])

In [10]:
x[(x > 0) & (x <= 70)]

array([1, 3, 1, 3])

In [11]:
x[[2, 5]]

array([ 3, 75])

Есть много сопособов создать в `numpy` вектор. Можно сделать это перечислением элементов, как выше для вектора `x`. А можно с помощью различных специальных функций.

In [12]:
y = np.arange(start=10, stop=20, step=2) # последнее значение не включается!
y

array([10, 12, 14, 16, 18])

In [13]:
y = np.ones(5) # вектор длины 5 из единиц
y

array([1., 1., 1., 1., 1.])

In [14]:
y = np.zeros(4) # вектор длины 4 из нулей
y

array([0., 0., 0., 0.])

In [15]:
y = np.random.rand(5)  # случайный вектор, равномерное распределение на [0;1] 
y

array([0.3415712 , 0.51972915, 0.87653966, 0.15046545, 0.55317399])

In [16]:
y = np.ones_like(x) # вектор из единиц такой же длины как вектор x
y

array([1, 1, 1, 1, 1, 1, 1])

По сути вектор в `numpy` является одномерным массивом, что соответствует интуитивному определению вектора:

In [17]:
y.shape # размерность вектора

(7,)

Более подробно о том, как создавать векторы в `NumPy`, 
см. [документацию](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).

## 1.2 Матрицы

Можно создать матрицу!

In [18]:
A = np.array([[1, 2, 3], [2, 5, 6], [6, 7, 4]])
A

array([[1, 2, 3],
       [2, 5, 6],
       [6, 7, 4]])

In [19]:
A.shape # размерность

(3, 3)

In [20]:
A[2]    # вторая строка матрицы

array([6, 7, 4])

In [21]:
A[:,1]  # первый столбец матрицы

array([2, 5, 7])

In [22]:
A[2][1] # можно срезать сначала строку, потом столбец

7

In [23]:
A[2,1]  # либос разу обе размерности

7

In [24]:
A[1:,1:] # можно найти срез

array([[5, 6],
       [7, 4]])

Более подробно о различных способах индексирования в массивах
см. [документацию](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

Булевы массивы позволяют получать элементы, стоящие на тех же местах что и True в булевом массиве (выражение в квадратных скобках):

In [25]:
is_even = A % 2 == 0 # проверяем четность элементов
print(is_even)

[[False  True False]
 [ True False  True]
 [ True False  True]]


In [26]:
A[is_even]

array([2, 2, 6, 6, 4])

In [27]:
np.where(A % 2 == 0)  # номера строк и столбцов

(array([0, 1, 1, 2, 2]), array([1, 0, 2, 0, 2]))

In [28]:
idx = np.where(A % 2 == 0)
A[idx]

array([2, 2, 6, 6, 4])

Можно создавать специальные матрицы разными функциями, по аналогии с векторами. 

In [29]:
np.ones((3,3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.zeros((3,3)) 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.random.normal(size=(3,3))

array([[ 0.45658939, -1.45582758, -0.6748513 ],
       [-3.12376698, -1.92593155, -0.88180818],
       [-0.56787489, -1.02648586, -0.89152581]])

In [32]:
np.eye(5) # единичная матрица

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Можно изменять размерности, если число элементов позволяет это сделать.

In [33]:
v = np.arange(0, 24, 2)
v

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [34]:
v.shape

(12,)

In [35]:
v.reshape((3, 4))

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [36]:
v.reshape((3, 6))

ValueError: cannot reshape array of size 12 into shape (3,6)

In [37]:
v.reshape((3, -1)) # -1 => если возможно, найди размерность второй оси автоматически

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [38]:
D = np.random.normal(size=(3,3,3))
D.shape

(3, 3, 3)

In [39]:
D  # Вектор из матриц

array([[[ 0.18544533,  1.67367841, -1.39530977],
        [ 0.62617895, -1.3397119 ,  0.46984535],
        [ 0.76851825, -0.06056621, -0.56411855]],

       [[-0.611388  ,  0.1436543 ,  0.73396897],
        [ 1.41914724,  0.19984592,  1.72304916],
        [-0.24084836, -0.05065286,  0.6603122 ]],

       [[ 2.14212664,  0.65826653, -0.72244315],
        [-1.73734235, -0.6807925 , -0.81136758],
        [ 1.46364485,  0.60877046,  0.06454216]]])

Массивы можно объединять:



In [40]:
A = np.array([[1, 2], [3, 4]])
np.hstack((A, np.zeros(A.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.]])

In [41]:
np.vstack((A, np.zeros(A.shape)))

array([[1., 2.],
       [3., 4.],
       [0., 0.],
       [0., 0.]])

In [42]:
np.concatenate((A, np.eye(A.shape[1])), axis=0)

array([[1., 2.],
       [3., 4.],
       [1., 0.],
       [0., 1.]])

<img src="https://i.ibb.co/JqsBZBF/matricesconcat.png"  height="600"> 

Более подробно о том, как создавать массивы в `numpy`, 
см. [документацию](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).

## 1.3 Векторы, вектор-строки и вектор-столбцы

In [43]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [44]:
b = np.array([[1], [2], [3]])
b

array([[1],
       [2],
       [3]])

In [45]:
a.shape

(3,)

In [46]:
b.shape

(3, 1)

__Обратите внимание:__ _вектор_ (одномерный массив) и _вектор-столбец_ или _вектор-строка_ (двумерные массивы) являются различными объектами в `numpy`, хотя математически задают один и тот же объект. В случае одномерного массива кортеж `shape` состоит из одного числа и имеет вид `(n,)`, где `n` — длина вектора. В случае двумерных векторов в `shape` присутствует еще одна размерность, равная единице. 

В большинстве случаев неважно, какое представление использовать, потому что часто срабатывает приведение типов. Но некоторые операции не работают для одномерных массивов. Например, транспонирование:

In [47]:
a.T

array([1, 2, 3])

In [48]:
b.T

array([[1, 2, 3]])

## 1.4  Умножение матриц и векторов-столбцов

Матрицы можно умножать!

<img src="https://i.ibb.co/xq6tgns/matrixmult.png"  height="400"> 

In [49]:
A = np.array([[1, 0], [0, 1]])
B = np.array([[4, 1], [2, 2]])
A@B

array([[4, 1],
       [2, 2]])

In [50]:
np.dot(A, B)

array([[4, 1],
       [2, 2]])

In [51]:
x = np.array([1, 2])
B@x

array([6, 6])

__Обратите внимание:__ операция __`*`__ производит над матрицами покоординатное умножение, а не матричное!

<img src="https://i.ibb.co/CtC2RqY/elementwisemult.png"  height="250"> 

In [52]:
A * B

array([[4, 0],
       [0, 2]])

Базовые арифметические операции над массивами выполняются поэлементно.

In [53]:
A + B

array([[5, 1],
       [2, 3]])

In [54]:
A * 1.0 / B

array([[0.25, 0.  ],
       [0.  , 0.5 ]])

In [55]:
A + 1 

array([[2, 1],
       [1, 2]])

In [56]:
3 * A

array([[3, 0],
       [0, 3]])

In [57]:
A ** 2

array([[1, 0],
       [0, 1]])

Поскольку операции выполняются поэлементно, операнды бинарных операций должны иметь одинаковый размер. Тем не менее, операция может быть корректно выполнена, если размеры операндов таковы, что они могут быть расширены до одинаковых размеров. Данная возможность называется [broadcasting](http://www.scipy-lectures.org/intro/numpy/operations.html#broadcasting):


<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png"  height="600"> 

In [58]:
A = np.tile(np.arange(0, 40, 10), (3, 1)).T 
A

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [59]:
A + np.array([0, 1, 2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

## 1.5 Другие операции над матрицами

In [60]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
A  

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [61]:
A.T  # Транспонирование

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6, 10]])

In [62]:
np.linalg.det(A) # Определитель

-3.000000000000001

In [63]:
np.linalg.matrix_rank(A) # Ранг матрицы

3

In [64]:
np.diag(A) # главная диагональ

array([ 1,  5, 10])

In [65]:
B = np.linalg.inv(A) # обратная матрица
B

array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

In [66]:
A@B # Единичная матрица

array([[ 1.00000000e+00, -4.44089210e-16, -1.11022302e-16],
       [ 4.44089210e-16,  1.00000000e+00, -2.22044605e-16],
       [ 4.44089210e-16,  8.88178420e-16,  1.00000000e+00]])

In [67]:
np.sum((A@B - np.eye(3))**2) # невязка между элементами

2.3296048607308005e-30

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям. Если речь о матрицах, то по строкам или столбцам:

In [68]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [69]:
A.sum()

46

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам.

In [70]:
np.sum(A, axis=1)

array([ 6, 15, 25])

In [71]:
np.sum(A, axis=0)

array([12, 15, 19])

In [72]:
A.sum(axis=0) # то же самое, но как метод

array([12, 15, 19])

# 2. Решаем задачи

В будущем вы будете учить анализ данных. Там неожиданно выяснится, что любые данные - это матрица. Там-то вы и увидите впервые всю мощь numpy. 

### Задачка 1 (максимум перед нулем) 

 
Реализуйте функцию, возвращающую максимальный элемент в векторе $x$ среди элементов, перед которыми стоит нулевой. 

Например, для `x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])` ответом является `5`. Если нулевых элементов нет, функция должна возвращать `None`.

In [73]:
x = np.array([1, 5, 8, 6, 6, 1, 7, 4, 4, 0])
y = np.random.randint(9, size=10)

def max_element_before_zero(x):
    shift_by_one = np.hstack((1, x))
    bool_array = (shift_by_one == 0)[:np.size(shift_by_one) - 1]
    if np.size(x[bool_array]) == 0:
        return None
    else:
        return np.max(x[bool_array])
    
print('Случайный вектор:', x, 'Максимальный элемент:', max_element_before_zero(x), sep='\n')
print(' ')
print('Случайный вектор:', y, 'Максимальный элемент:', max_element_before_zero(y), sep='\n')

Случайный вектор:
[1 5 8 6 6 1 7 4 4 0]
Максимальный элемент:
None
 
Случайный вектор:
[2 2 2 3 0 1 5 2 7 4]
Максимальный элемент:
1


__Зачем?__ 

К вам в голову тут должна была прийти мысль: "Зачем? Можно же использовать цикл!". Да, можно. Но векторные вычисления работают на порядок быстрее. Часто сделать их намного удобнее, чем написать цикл.

### Задачка 2 (нормировка) 

Есть матрица $X$. Нужно отнормировать её столбцы к отрезку $[0;1]:$

$$
x^{*} = \frac{x−min(x)}{max(x)−min(x)}
$$

In [74]:
X = np.random.normal(size=(5,5))
X

array([[-0.04680121, -0.80420161, -0.92505152,  0.77883576,  1.52170839],
       [ 1.39894531,  0.94030964,  0.34955328, -0.46798541, -1.1556363 ],
       [-0.79306085, -1.80161223, -0.17186289, -0.9005578 , -0.56421176],
       [ 0.22740949,  0.82382974, -0.25152303, -1.52466721,  1.14291371],
       [ 0.90505835, -0.34914135, -0.87579163, -1.54471848, -2.44219184]])

In [75]:
(X - X.min(axis=0))/(X.max(axis=0) - X.min(axis=0))

array([[0.34044596, 0.36376333, 0.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 0.46339915, 0.32456809],
       [0.        , 0.        , 0.59091934, 0.27723075, 0.47377077],
       [0.46554173, 0.95751889, 0.52842143, 0.00862957, 0.9044389 ],
       [0.77468724, 0.5297273 , 0.03864719, 0.        , 0.        ]])

__Зачем?__ 

К вам в голову тут должна была прийти мысль: "Зачем вообще делать это?". 

Обычно в машинном обучении по строчкам записывают наблюдения, по столбцам разные признаки. Часто между объектами надо считать расстояния. Представим, что у нас в выборке два наблюдения. Петя, который весит $50$ кг при росте $1$ метр. И Вася, который вести $75$ кг при росте в $1.5$ метра. То есть Петя описывается вектором $(50, 1)$, а Вася $(75, 1.5)$. 

Если нам надо вычислить между парнями расстояние, мы будем делать это так:

In [76]:
print((50 - 75) ** 2)
print((1 - 1.5) ** 2)
(50 - 75) ** 2 + (1 - 1.5) ** 2

625
0.25


625.25

Намного больше внимания уделяется весу. Чтобы такого не возникало, надо отнормировать все признаки к одной шкале. Например, отрезку $[0;1]$. 

> Если хотите узнать о том как линал используется в машинном обучении больше, смотрите небольшой видос про рекомендательные системы ["От матрицы до больших данных"](https://www.youtube.com/watch?v=Or119IXozCM)

### Задачка 3 (ближайший в матрице) 

Реализуйте функцию, принимающую на вход матрицу $X$ и некоторое число $a$ и возвращающую ближайший к числу элемент матрицы. А потом перепишите её так, чтобы она возвращала самый дальний элемент. 

In [77]:
def nearest_value(X, v):
    Y = np.abs(X - v)
    m = np.min(Y)
    inds = np.where(Y == m)
    return X[inds[0][0], inds[1][0]]

X = np.arange(0,10).reshape((2, 5))
v = 3.6
print ('Матрица:', X, 'Число:', v, 'Ближайший к числу элемент матрицы:', nearest_value(X, v), sep='\n')

Матрица:
[[0 1 2 3 4]
 [5 6 7 8 9]]
Число:
3.6
Ближайший к числу элемент матрицы:
4


In [78]:
# Решение в одну строку
def get_nearest_value(X, v):
    return X.reshape(1, -1)[0][np.argmin(np.abs(X - v))]

print ('Матрица:', X, 'Число:', v, 
       'Ближайший к числу элемент матрицы:', get_nearest_value(X, v), sep='\n')

Матрица:
[[0 1 2 3 4]
 [5 6 7 8 9]]
Число:
3.6
Ближайший к числу элемент матрицы:
4


### Задачка 4 (ближайшая строка в матрице) 

Усложним предыдущую задачу! Дана матрица $X$ и вектор $v$. Нужно найти в матрице $X$ строку, которая будет ближе всего к вектору $v$. 

In [79]:
X = np.random.binomial(100, 0.5, size=(5,3))/100
v = np.random.uniform(size=(5,1))
X, v

(array([[0.53, 0.56, 0.53],
        [0.55, 0.55, 0.58],
        [0.55, 0.53, 0.53],
        [0.53, 0.51, 0.47],
        [0.54, 0.55, 0.5 ]]),
 array([[0.80073145],
        [0.42416672],
        [0.07591761],
        [0.6981656 ],
        [0.76300473]]))

In [80]:
R = (X - v)**2
R

array([[0.07329552, 0.05795163, 0.07329552],
       [0.01583401, 0.01583401, 0.02428401],
       [0.22475411, 0.20619081, 0.20619081],
       [0.02827967, 0.03540629, 0.05205954],
       [0.04973111, 0.04537101, 0.06917149]])

In [81]:
z = np.sqrt(np.sum(R, axis=0))
z

array([0.62601471, 0.60062781, 0.65192129])

In [82]:
X[:, np.where(z == np.min(z))].T

array([[[0.56, 0.55, 0.53, 0.51, 0.55]]])

__Зачем?__ 

Зачем вообще кому-то нужны задания 3 и 4?! В машинном обучения всюду вектора! Например, есть волшебная технология __word2vec__. В ней все слова превращают в вектора так, чтобы в них был закодирован смысл слова. В итоге неожиданно оказывается, что эти вектора можно складывать и вычитать. Если взять вектор _король_, вычесть из него _мужчина_ и добавить _женщина_, внезапно получится вектор, самым близким к которому является _королева_. 

Все эти вычисления удобно делать в `numpy`, написанными нами функциями. Поиграться с такой моделью и калькулятором слов можно [на сайте resvectores](https://rusvectores.org/ru/calculator/#)

### Задачка 5 (расстояние между всеми строками) 

Найдите расстояние между каждой строкой матрицы A и каждой строкой матрицы B. Запишите результат в виде матрицы. 

In [83]:
A = np.random.normal(size=(3,4))
B = np.random.normal(size=(3,4))
print(A)
print('')
print(B)

[[-0.53717956  0.76389451 -0.16415534  0.50728148]
 [-0.34657897 -0.62101538  0.16065614  0.3156775 ]
 [-0.26135304 -0.3637507   2.66373288 -0.78062163]]

[[ 1.79306036 -0.03926721 -1.14399283  1.28950114]
 [ 0.61866969  0.31474284  1.68350924 -0.95156661]
 [ 1.78575377 -0.2751638  -2.21442265 -0.71017225]]


In [84]:
np.sqrt(np.sum((A - B)**2, axis=1))

array([2.76532745, 2.39423006, 5.29148924])

In [85]:
A.shape

(3, 4)

In [86]:
A[None, :, :].shape

(1, 3, 4)

In [87]:
A[:, None, :]

array([[[-0.53717956,  0.76389451, -0.16415534,  0.50728148]],

       [[-0.34657897, -0.62101538,  0.16065614,  0.3156775 ]],

       [[-0.26135304, -0.3637507 ,  2.66373288, -0.78062163]]])

In [88]:
A[:, :, None]

array([[[-0.53717956],
        [ 0.76389451],
        [-0.16415534],
        [ 0.50728148]],

       [[-0.34657897],
        [-0.62101538],
        [ 0.16065614],
        [ 0.3156775 ]],

       [[-0.26135304],
        [-0.3637507 ],
        [ 2.66373288],
        [-0.78062163]]])

In [89]:
np.array([[ 1.38401572],  [1.40520531],  [1.39232575], [-0.88064082]]) - B

ValueError: operands could not be broadcast together with shapes (4,1) (3,4) 

In [90]:
np.array([[1.38401572,  1.40520531,  1.39232575, -0.88064082]]) - B

array([[-0.40904464,  1.44447252,  2.53631858, -2.17014196],
       [ 0.76534603,  1.09046247, -0.29118349,  0.07092579],
       [-0.40173805,  1.68036911,  3.6067484 , -0.17046857]])

In [91]:
A[:, None, :] - B

array([[[-2.33023991,  0.80316173,  0.97983749, -0.78221966],
        [-1.15584924,  0.44915168, -1.84766458,  1.45884809],
        [-2.32293333,  1.03905832,  2.05026731,  1.21745373]],

       [[-2.13963933, -0.58174816,  1.30464897, -0.97382364],
        [-0.96524866, -0.93575821, -1.5228531 ,  1.26724411],
        [-2.13233274, -0.34585157,  2.37507879,  1.02584975]],

       [[-2.0544134 , -0.32448349,  3.8077257 , -2.07012277],
        [-0.88002273, -0.67849354,  0.98022363,  0.17094498],
        [-2.04710682, -0.0885869 ,  4.87815552, -0.07044938]]])

In [92]:
np.sqrt(np.sum((A[:, None, :] - B) ** 2, axis= 2))

array([[2.76532745, 2.6607944 , 3.48732721],
       [2.75080512, 2.39423006, 3.37043368],
       [4.80729521, 1.49159446, 5.29148924]])

In [93]:
np.sqrt(np.sum((A - B)**2, axis=1))

array([2.76532745, 2.39423006, 5.29148924])

### Больше заданий для практики можно найти: 

- В [необязательном контесте](https://contest.yandex.ru/contest/25960/problems/) вас ждут простые и не очень задачи на numpy
- В сборнике [100 упражнений на `numpy`](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md), там же [вариант без решения с подсказками.](https://github.com/rougier/numpy-100) Некоторые упражнения странные и бесполезные. 

Ещё можно почитать [numpy tutorial](http://cs231n.github.io/python-numpy-tutorial/)

------------------------

# 3. Бонус-трек: линейная алгебра

> Эту часть тетрадки мы __НЕ будем__ делать на семинаре. Её можно помотреть после него. Внутри много полезного функционала. Но ясное дело далеко не весь. Если хочется больше линала, да ещё и с python, добро пожаловать [курс по линал от ББ Демешева](https://www.coursera.org/learn/lineinaya-algebra) 

В этой части тетрадки мы поглубже поссмотим на функционал пакета. Далее нам понабится модуль `numpy.linalg`, реализующий некоторые приложения линейной алгебры.

## 3.1 Нормы векторов 

Вспомним некоторые нормы, которые можно ввести в пространстве $\mathbb{R}^{n}$, и рассмотрим, с помощью каких библиотек и функций их можно вычислять в `numpy`.  Для вычисления различных норм мы используем функцию `numpy.linalg.norm(x, ord=None, ...)`, где `x` — исходный вектор, `ord` — параметр, определяющий норму (мы рассмотрим два варианта его значений — 1 и 2). 

### $\ell_{2}$ норма

$\ell_{2}$ норма (также известная как евклидова норма)
для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ вычисляется по формуле:

$$
 \left\Vert x \right\Vert_{2} = \sqrt{\sum_{i=1}^n \left( x_{i} \right)^2}.
$$

Ей в функции `numpy.linalg.norm(x, ord=None, ...)` соответствует параметр `ord=2`.

In [94]:
from numpy.linalg import norm

In [95]:
a = np.array([1, 2, -3])
norm(a, ord=2)

3.7416573867739413

### $\ell_{1}$ норма

$\ell_{1}$ норма 
(также известная как [манхэттенское расстояние](https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D1%81%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5_%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D1%81%D0%BA%D0%B8%D1%85_%D0%BA%D0%B2%D0%B0%D1%80%D1%82%D0%B0%D0%BB%D0%BE%D0%B2))
для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ вычисляется по формуле:

$$
 \left\Vert x \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} \right|.
$$

Ей в функции `numpy.linalg.norm(x, ord=None, ...)` соответствует параметр `ord=1`.

In [96]:
a = np.array([1, 2, -3])
norm(a, ord=1)

6.0

Более подробно о том, какие еще нормы (в том числе матричные) можно вычислить, см. [документацию](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linalg.norm.html). 

## 3.2   Расстояния между векторами

Для двух векторов $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ и $y = (y_{1}, \dots, y_{n}) \in \mathbb{R}^{n}$ $\ell_{1}$ и $\ell_{2}$ раccтояния вычисляются по следующим формулам соответственно:

$$
 \rho_{1}\left( x, y \right) = \left\Vert x - y \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} - y_{i} \right|
$$

$$
 \rho_{2}\left( x, y \right) = \left\Vert x - y \right\Vert_{2} = 
 \sqrt{\sum_{i=1}^n \left( x_{i} - y_{i} \right)^2}.
$$

In [97]:
a = np.array([1, 2, -3])
b = np.array([-4, 3, 8])

In [98]:
norm(a - b, ord=1)

17.0

In [99]:
norm(a - b, ord=2)

12.12435565298214

Также расстояние между векторами можно посчитать с помощью функции  `scipy.spatial.distance.cdist(XA, XB, metric='euclidean', p=2, ...)` из модуля `scipy`, предназначенного для выполнения научных и инженерных расчётов. 

In [100]:
from scipy.spatial.distance import cdist

`scipy.spatial.distance.cdist(...)` требует, чтобы размерность `XA` и `XB` была как минимум двумерная. По этой причине для использования этой функции необходимо преобразовать _векторы_, которые мы рассматриваем в этом ноутбуке, к _вектор-строкам_ с помощью способов, которые мы рассмотрим ниже. 

Параметры `XA, XB` — исходные вектор-строки, а `metric` и `p` задают метрику расстояния
(более подробно о том, какие метрики можно использовать, см. [документацию](http://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.spatial.distance.cdist.html)).

Первый способ из _вектора_ сделать _веткор-строку (вектор-столбец)_ — это использовать _метод_ `array.reshape(shape)`, где параметр `shape` задает размерность вектора (кортеж чисел).

In [101]:
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])

print('Вектор a:', a)
print('Его размерность:', a.shape)
print('Вектор b:', b)
print('Его размерность:', b.shape)

Вектор a: [ 6  3 -5]
Его размерность: (3,)
Вектор b: [-1  0  7]
Его размерность: (3,)


In [102]:
a = a.reshape((1, 3))
b = b.reshape((1, 3))

print('После применения метода reshape:\n')
print('Вектор-строка a:', a)
print('Его размерность:', a.shape)
print('Вектор-строка b:', b)
print('Его размерность:', b.shape)

После применения метода reshape:

Вектор-строка a: [[ 6  3 -5]]
Его размерность: (1, 3)
Вектор-строка b: [[-1  0  7]]
Его размерность: (1, 3)


In [103]:
print('Манхэттенское расстояние между a и b (через cdist):', cdist(a, b, metric='cityblock'))

Манхэттенское расстояние между a и b (через cdist): [[22.]]


Заметим, что после применения этого метода размерность полученных вектор-строк будет равна `shape`. Следующий метод позволяет сделать такое же преобразование, но не изменяет размерность исходного вектора.  

В `numpy` к размерностям объектов можно добавлять фиктивные оси с помощью `np.newaxis`. Для того, чтобы понять, как это сделать, рассмотрим пример:

In [104]:
d = np.array([3, 0, 8, 9, -10])

print('Вектор d:', d)
print('Его размерность:', d.shape)

Вектор d: [  3   0   8   9 -10]
Его размерность: (5,)


In [105]:
print('Вектор d с newaxis --> вектор-строка:\n', d[np.newaxis, :])
print('Полученная размерность:', d[np.newaxis, :].shape)
print(' ')
print('Вектор d с newaxis --> вектор-столбец:\n', d[:, np.newaxis])
print('Полученная размерность:', d[:, np.newaxis].shape)

Вектор d с newaxis --> вектор-строка:
 [[  3   0   8   9 -10]]
Полученная размерность: (1, 5)
 
Вектор d с newaxis --> вектор-столбец:
 [[  3]
 [  0]
 [  8]
 [  9]
 [-10]]
Полученная размерность: (5, 1)


Важно, что `np.newaxis` добавляет к размерности ось, длина которой равна 1 (это и логично, так как количество элементов должно сохраняться). Таким образом, надо вставлять новую ось там, где нужна единица в размерности. 

Теперь посчитаем расстояния с помощью `scipy.spatial.distance.cdist(...)`, используя `np.newaxis` для преобразования векторов:

In [106]:
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])

print('Евклидово расстояние между a и b (через cdist):', cdist(a[np.newaxis, :], 
                                                               b[np.newaxis, :], 
                                                               metric='euclidean'))

Евклидово расстояние между a и b (через cdist): [[14.2126704]]


Эта функция также позволяет вычислять попарные расстояния между множествами векторов. Например, пусть у нас имеется матрица размера $m_{A} \times n$. Мы можем рассматривать ее как описание некоторых $m_{A}$ наблюдений в $n$-мерном пространстве. Пусть также имеется еще одна аналогичная матрица размера $m_{B} \times n$, где  $m_{B}$ векторов в том же $n$-мерном пространстве. Часто необходимо посчитать попарные расстояния между векторами первого и второго множеств. 

В этом случае можно пользоваться функцией `scipy.spatial.distance.cdist(XA, XB, metric='euclidean', p=2, ...)`, где в качестве `XA, XB` необходимо передать две описанные матрицы. Функция возаращает матрицу попарных расстояний размера $m_{A} \times m_{B}$, где элемент матрицы на $[i, j]$-ой позиции равен расстоянию между $i$-тым вектором первого множества и $j$-ым вектором второго множества. 

В данном случае эта функция предподчительнее `numpy.linalg.norm(...)`, так как она вычисляет попарные расстояния быстрее и эффективнее. 

## 3.3 Скалярное произведение и угол между векторами

In [107]:
a = np.array([0, 5, -1])
b = np.array([-4, 9, 3])

Скалярное произведение в пространстве $\mathbb{R}^{n}$ для двух векторов $x = (x_{1}, \dots, x_{n})$ и $y = (y_{1}, \dots, y_{n})$ определяется как:

$$
\langle x, y \rangle = \sum_{i=1}^n x_{i} y_{i}.
$$

Скалярное произведение двух векторов можно вычислять помощью функции `numpy.dot(a, b, ...)` или _метода_ `vec1.dot(vec2)`, где `vec1` и `vec2` — исходные векторы. Также эти функции подходят для матричного умножения, о котором речь пойдет в следующем уроке. 

In [108]:
np.dot(a, b) # через функцию

42

In [109]:
a.dot(b) # через метод

42

In [110]:
a@b # через матричное умножение

42

Длиной вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ называется квадратный корень из скалярного произведения, то есть длина равна евклидовой норме вектора:

$$
\left| x \right| = \sqrt{\langle x, x \rangle} = \sqrt{\sum_{i=1}^n x_{i}^2} =  \left\Vert x \right\Vert_{2}.
$$

Теперь, когда мы знаем расстояние между двумя ненулевыми векторами и их длины, мы можем вычислить угол между ними через скалярное произведение:

$$
\langle x, y \rangle = \left| x \right| | y | \cos(\alpha)
\implies \cos(\alpha) = \frac{\langle x, y \rangle}{\left| x \right| | y |},
$$

где $\alpha \in [0, \pi]$ — угол между векторами $x$ и $y$.

In [111]:
cos_angle = np.dot(a, b) / norm(a) / norm(b)
cos_angle  # косинус угла

0.8000362836474323

In [112]:
np.arccos(cos_angle) # сам угол

0.6434406336093618

Более подробно о том, как вычислять скалярное произведение в `numpy`, 
см. [документацию](http://docs.scipy.org/doc/numpy/reference/routines.linalg.html#matrix-and-vector-products).

## 3.4 Системы линейных уравнений

__Системой линейных алгебраических уравнений__ называется система вида $Ax = b$, где $A \in \mathbb{R}^{n \times m}, x \in \mathbb{R}^{m \times 1}, b \in \mathbb{R}^{n \times 1}$. В случае квадратной невырожденной матрицы $A$ решение системы единственно.

В `numpy` решение такой системы можно найти с помощью функции `numpy.linalg.solve(a, b)`, где первый аргумент — матрица $A$, второй — столбец $b$.

In [113]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
x

array([2., 3.])

Убедимся, что вектор $x$ действительно является решением системы:

In [114]:
A.dot(x)

array([9., 8.])

Бывают случаи, когда решение системы не существует. Но хотелось бы все равно "решить" такую систему. Логичным кажется искать такой вектор $x$, который минимизирует выражение $\left\Vert Ax - b\right\Vert^{2}$ — так мы приблизим выражение $Ax$ к $b$.

В `numpy` такое псевдорешение можно искать с помощью функции `numpy.linalg.lstsq(a, b, ...)`, где первые два аргумента такие же, как и для функции `numpy.linalg.solve()`. 

Помимо решения функция возвращает еще три значения, которые нам сейчас не понадобятся.

In [115]:
A = np.array([[0, 1], [1, 1], [2, 1], [3, 1]])
b = np.array([-1, 0.2, 0.9, 2.1])
x, res, r, s = np.linalg.lstsq(A, b)

/var/folders/95/tw3zkzk9035_zpzhx2ty33pn4qbhgy/T/ipykernel_36269/4083040527.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, res, r, s = np.linalg.lstsq(A, b)


In [116]:
A

array([[0, 1],
       [1, 1],
       [2, 1],
       [3, 1]])

In [117]:
b

array([-1. ,  0.2,  0.9,  2.1])

In [118]:
x

array([ 1.  , -0.95])

## 3.5 Собственные числа и собственные вектора матрицы

Для квадратных матриц определены понятия __собственного вектора__ и __собственного числа__.

Пусть $A$ — квадратная матрица и $A \in \mathbb{R}^{n \times n}$. __Собственным вектором__ матрицы $A$ называется такой ненулевой вектор $x \in \mathbb{R}^{n}$, что для некоторого $\lambda \in \mathbb{R}$ выполняется равенство $Ax = \lambda x$. При этом $\lambda$ называется __собственным числом__ матрицы $A$. Собственные числа и собственные векторы матрицы играют важную роль в теории линейной алгебры и ее практических приложениях.

В `numpy` собственные числа и собственные векторы матрицы вычисляются с помощью функции `numpy.linalg.eig(a)`, где `a` — исходная матрица. В качестве результата эта функция выдает одномерный массив `v` собственных чисел и двумерный массив `w`, в котором по столбцам записаны собственные вектора, так что вектор `w[:, i]` соотвествует собственному числу `v[i]`.

In [119]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

In [120]:
w

array([2., 3.])

In [121]:
v

array([[-0.89442719,  0.83205029],
       [ 0.4472136 , -0.5547002 ]])

__Обратите внимание:__ у вещественной матрицы собственные значения или собственные векторы могут быть комплексными.

## 3.6  Комплексные числа в питоне

__Комплексными числами__ называются числа вида $x + iy$, где $x$ и $y$ — вещественные числа, а $i$ — мнимая единица (величина, для которой выполняется равенство $i^{2} = -1$). Множество всех комплексных чисел обозначается буквой $\mathbb{C}$ (подробнее про комплексные числа см. [википедию](https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BC%D0%BF%D0%BB%D0%B5%D0%BA%D1%81%D0%BD%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE)).

В питоне комплескные числа можно задать следующим образом ( $j$ обозначает мнимую единицу):

In [122]:
a = 3 + 2j
a

(3+2j)

In [123]:
b = 1j
b

1j

In [124]:
a * a

(5+12j)

In [125]:
a / (4 - 5j)

(0.0487804878048781+0.5609756097560976j)

In [126]:
np.abs(a)

3.6055512754639896

In [127]:
np.sqrt(3**2 + 2**2)

3.605551275463989